syntax = "proto3";

package sql;

import "Common.proto";

//定义MySQL通讯节点
message sql_node {
  common.header head = 1;  //通讯头
  int32         type = 2;  //通讯类型
  bytes         msg  = 3;  //通讯具体
}

//初始化/更新MySQL连接
message sql_init {
  string ip             = 1;  //服务器ip地址
  uint32 port           = 2;  //服务器端口地址
  string user           = 3;  //用户名
  string password       = 4;  //用户密码
  string db             = 5;  //要连接的数据库
  uint32 InitSize       = 6;  //初始化连接
  uint32 MaxSize        = 7;  //最大连接量
  uint32 TimeMax        = 8;  //最大时间
  uint32 TimeOut        = 9;  //断连时间
  uint32 ThreadPoolSize = 10; //线程池数量
  uint32 Wait_Queue_Max = 11; //最大队列数
}

//查询节点
message select {
  int32  type = 1;//二级类型
  string msg  = 2;//具体消息
}

//mysql统一头
message sql_head {
  string table = 1;//数据库名
}

message CheckUser{
  sql_head head  = 1;//头节点
  string   name  = 2;//用户名
  string   email = 3;//邮箱
}

//mysql插入
message sql_insert {
  sql_head head = 1;
}

//mysql通用返回
message recv {
  common.header head = 1;
  string        msg  = 2;
}